apiVersion: v1
kind: Service
metadata:
  name: todo-chatbot-backend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: todo-chatbot-backend
