apiVersion: v1
kind: Service
metadata:
  name: todo-chatbot-frontend
  namespace: todo-chatbot
  labels:
    app: todo-chatbot-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: todo-chatbot-frontend
